BoxLayout:
    orientation: 'vertical'
#    orientation: 'horizontal'
    Button:
        text: "Clear"
        on_release:
            input_name.text = ''  # Reset the text field
            output_label.text = ''  # Reset the output label


    Button:
    TextInput:
        id: input_name
        text: ''
    Button:
        text: 'Greet'
        on_press: app.handle_greet()
    Label:
        text: 'Enter your name'
        color: (1, 1, 0, 1)
        id: output_label

